sudo: required
notifications:
  email:
    recipients:
      - karima.rafes@gmail.com
    on_success: always # default: change (other : never)
    on_failure: always # default: always

env:
  global:
    - URI="https://travis-ci.org/BorderCloud/tft-blazegraph/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Blazegraph"
    - VERSION="v2.2.0"
    - SPARQLSCOREDATABASE="134.158.74.247"

language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - docker pull bordercloud/tft-virtuoso7-stable
  - docker build -t tft-blazegraph .

script:
  -   docker run --privileged --name instance.tft-blazegraph -h tft-blazegraph -d tft-blazegraph
  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
  
  -   sleep 30
  -   docker network inspect bridge
  
  -   git clone --recursive https://github.com/BorderCloud/TFT.git
  -   cd TFT
  -   composer install 
#  -   php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
  -   php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt fuseki -tq http://172.17.0.2/blazegraph/namespace/test/sparql/ -tu http://172.17.0.2/blazegraph/namespace/test/sparql/ -r ${URI} -o ./junit --softwareName="${NAME}" --softwareDescribeTag=${VERSION}  --softwareDescribe="${TRAVIS_COMMIT}" 
  -   php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}

after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
#    docker push bordercloud/tft-blazegraph;
#    fi
