name: Test

# REFRESH THE VERSION NUMBER BEFORE TO START THIS WORKFLOW

on: workflow_dispatch

env:
    NAME: "Blazegraph"
    SOFTWARE_DESCRIBE: "Blazegraph is a triplestore and graph database, which is used in the Wikidata SPARQL endpoint."
    VERSION: "2.1.5" 
    SPARQLSCORE_DATABASE: "134.158.74.239"
#       SPARQLSCORE_DATABASE="172.18.0.6:8080" #local
    URI: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}       
    COMMIT: ${{github.sha}}
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            tools: composer
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '8'
      - name: Build image docker
        run: >-
            docker build --build-arg branch_blazegraph=BLAZEGRAPH_RELEASE_2_1_5 -t tft-blazegraph .
      - name: Start servers
        run:  |
            sudo docker-compose up -d
            sleep 30s
      - name: Setup TFT with Jmeter
        run: |
            git clone --recursive https://github.com/BorderCloud/TFT.git
            cd ./TFT
            composer install
            wget http://mirrors.standaloneinstaller.com/apache//jmeter/binaries/apache-jmeter-5.4.1.tgz
            tar xvzf apache-jmeter-5.4.1.tgz
            mv  apache-jmeter-5.4.1 jmeter
            rm apache-jmeter-5.4.1.tgz
            php -version
        #- name: Import tests
        #run: |
            #cd ./TFT
            #php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
      - name: Execute tests
        run: |
            cd ./TFT
            php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt fuseki -te http://172.18.0.2/blazegraph/namespace/test/sparql  -r ${URI} -o ./junit --softwareName="${NAME}" --softwareDescribeTag=${VERSION}  --softwareDescribe="${COMMIT}"
      - name: Read result
        run: |
            cd ./TFT
            php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}
      - name: Stop servers
        run:  |
          docker-compose stop
